version = 0.1

[default.deploy.parameters]
stack_name = "emoverse-ai-prod"
resolve_s3 = true
s3_prefix = "emoverse-ai-prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
