[theme]
primaryColor = "#f093fb"
backgroundColor = "#90EE90"
secondaryBackgroundColor = "#FFF59D"
textColor = "#2d3748"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
